### ISSUE TITLE
[MazSelect is not loading it's own correct style till i manually include the MazPhoneNumberInput][<MazSelect>]

### ISSUE THREAD

**Issue by hadelnasr** [LouisMazel/maz-ui#1188] opened 2024-12-08 12:31 UTC
## Describe the bug

When i have a page loading only the MazSelect component, it's UI is not loaded correctly as show below
![Screenshot from 2024-12-08 14-20-00](https://github.com/user-attachments/assets/5966d73f-6e6a-4eb0-9937-93953459faed)

The weird issue here that it's only fixed when i import the MazPhoneNumberInput component only, as it's internally loading MazPhoneNumberInput.css file which somehow fixes the design

![Screenshot from 2024-12-08 14-29-00](https://github.com/user-attachments/assets/f1af21e6-12a7-447d-a913-a95b02a189c9)

Any suggestions?

## To Reproduce

Add MazSelect component only => design issue
Add MazPhoneNumberInbut with it => design fixed for the MazSelect

## Expected behavior

Loading only MazSelect should be fixing the design

## Screenshots
![Screenshot from 2024-12-08 14-20-00](https://github.com/user-attachments/assets/7739507a-1a05-4212-8bb3-cea36240ac4c)
![Screenshot from 2024-12-08 14-29-00](https://github.com/user-attachments/assets/58cbdbce-2665-434f-8690-6cf7b8d4775d)

## Desktop (please complete the following information)

- Linux
- Browser chrome
- Version [e.g. 3.49.2]

**Comment by LouisMazel** [comment] 2024-12-08 12:44
HI @hadelnasr, 

Indeed it's strange, it's the CSS of the input that doesn't load...

I'll look at what's happening, I can reproduce this: https://stackblitz.com/edit/maz-ui-vue3-select?file=src/App.vue,package.json

**Comment by hadelnasr** [comment] 2024-12-08 14:09
@LouisMazel it seems to me that the mazSelect component is seeking a css attributes found in the mazPhoneNumberInput component

**Comment by LouisMazel** [comment] 2024-12-08 14:46
This is because the MazInput CSS file used by MazSelect is not loaded.
I don't know why it works well with MazPhoneNumberInput and not with MazSelect. This seems to be a bug in Vite.
I have to investigate

**Comment by LouisMazel** [comment] 2024-12-08 19:32
Fixed in [v3.49.3](https://github.com/LouisMazel/maz-ui/releases/tag/v3.49.3)

F.Y.I: It's was an error with the chunk hashs.

**Closed by LouisMazel** 2024-12-08 19:32 UTC
Labels: BUG FIX

**Comment by hadelnasr** [comment] 2024-12-09 09:15
@LouisMazel thanks for your fast response as usual

Are you sure that v3.49.3 is live now? as when i try to install it it keeps saying

`pm error code ETARGET
npm error notarget No matching version found for maz-ui@3.49.3.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
`

**Comment by LouisMazel** [comment] 2024-12-09 09:44
NPM was in maintenance yesterday, the pipeline has failed while publishing.
I will rerun it this morning.

I will keep you in touch when is good :)

**Comment by LouisMazel** [comment] 2024-12-09 12:59
All good now :)
