### ISSUE TITLE
[BUG] Country code dropdown unexpectedly closes when using the scroll bar in modal with phone input

### ISSUE THREAD

**Issue by nttint20** [LouisMazel/maz-ui#1174] opened 2024-10-18 07:41 UTC
Bug Description: When using the phone input inside a modal dialog with Bootstrap-Vue, the country code selection dropdown unexpectedly closes whenever the scroll bar is used to browse through the list of countries.

Expected Behavior: The country code dropdown should remain open while using the scroll bar to scroll through the list of available countries.

Desktop Environment:

- Operating System: Windows
- Browser: Google Chrome

If a fix is available, please let me know which version includes the fix so I can update the code accordingly.

**Comment by LouisMazel** [comment] 2024-10-20 11:47
Hi @nttint20,

I can't reproduce your bug, I tested with stackblitz: https://stackblitz.com/edit/bootstrap-vue-maz-ui?file=components/HelloBootstrap.vue

The modal stays open when I use the scrollbar with Windows and Chrome. 

Can you provide a reproduction link (with stackblitz or other) with your code? 

If you want to contribute, the version doesn't matter, just open a new PR 😊

**Comment by donald-nguyen-eh** [comment] 2024-10-20 12:04
Hi @LouisMazel 

Thanks for your response! I’m currently using Vue 2 with Maz UI version 2.3.13. From what I see in your example on Stackblitz, it seems like you’re testing with Maz UI version 3.47.1 and Vue version 3.5.12.

Could you confirm if the issue is fixed in Maz UI 3.x? If so, I believe that might be why you’re not able to reproduce the issue with the newer version. Since I’m still using Vue 2 and Maz UI 2.3.13, could it be a version-specific bug that’s resolved in the newer release?

If that’s the case, I’ll look into upgrading. Let me know your thoughts!

**Comment by LouisMazel** [comment] 2024-10-20 12:17
Oh ok, that's why!

Yes, this issue is fixed in the v3. I encourage you to upgrade your versions, the v2 of maz-ui is unmaintained now. 
The new version is really more efficient.

Thanks for your feedback.

**Closed by LouisMazel** 2024-10-20 12:17 UTC
Labels: BUG FIX

**Comment by donald-nguyen-eh** [comment] 2024-10-20 12:19
Thank you for the clarification! I really appreciate your help. I’ll work on upgrading to the latest version as you’ve suggested. Thanks again for your support and for building such a great framework!
